crm/client/urls.py
from django.urls import path

from . import views

app_name = 'clients'


urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>', views.clients_detail, name='detail'),
    path('add-client/', views.add_client, name='add'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
    path('<int:pk>/add_comment/', views.clients_detail, name='add_comment'),
    path('export/', views.clients_export, name='export'),
]

crm/crm/urls.py
from core.views import about, index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path
from userprofile.forms import LoginForm

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path(
        "log-in/",
        views.LoginView.as_view(
            template_name="userprofile/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("log-out/", views.LogoutView.as_view(), name="logout"),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/leads/", include("lead.urls")),
    path("dashboard/teams/", include("team.urls")),
    path("dashboard/clients/", include("client.urls")),
    path("dashboard/", include("userprofile.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='index'),
]

crm/lead/urls.py
from django.urls import path
from . import views


app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),

]

crm/team/urls.py
from django.urls import path

from . import views

app_name = "team"

urlpatterns = [
    path("", views.teams_list, name="list"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/edit/", views.edit_team, name="edit"),
    path("<int:pk>/activate/", views.teams_activate, name="activate"),
]

crm/core/models.py
from django.db import models

# Create your models here.

crm/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

crm/core/templates/core/partials/footer.html
<footer class="py-8 text-center bg-gray-200">
    <p class="text-xs text-gray-700">Copyright (c) 2022 - Simple CRM</p>
</footer>

crm/core/templates/core/partials/nav.html
<nav class="py-6 px-6 flex justify-between bg-violet-500">
    <a href="/" class="text-white">Simple CRM</a>

    <div class="space-x-4">
        <a href="{% url 'about' %}" class="text-white">О нас</a>

        {% if request.user.is_authenticated %}
        <a href="{% url 'team:detail' active_team.id %}" class='text-white'>{{ active_team.name }}</a>

        <a href="{% url 'dashboard:index' %}" class='py-4 px-6 bg-violet-600 rounded-xl text-white'>Статистика</a>
        <a href="{% url 'leads:list' %}" class='py-4 px-6 bg-violet-600 rounded-xl text-white'>Заявки</a>
        <a href="{% url 'clients:list' %}" class='py-4 px-6 bg-violet-600 rounded-xl text-white'>Клиенты</a>

        <a href="{% url 'userprofile:myaccount' %}" class='py-4 px-6 bg-violet-900 rounded-xl text-white'>Профиль</a>
        {% else %}
        <a href="{% url 'login' %}" class="py-4 px-6 bg-violet-600 rounded-xl text-white">Войти</a>
        <a href="{% url 'userprofile:signup' %}" class="py-4 px-6 bg-violet-300 rounded-xl text-white">Регистрация</a>
        {% endif %}
    </div>

</nav>