crm/client/urls.py
from django.urls import path

from . import views

app_name = 'clients'


urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>', views.clients_detail, name='detail'),
    path('add-client/', views.add_client, name='add'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
    path('<int:pk>/add_comment/', views.clients_detail, name='add_comment'),
    path('export/', views.clients_export, name='export'),
]

crm/crm/urls.py
from core.views import about, index
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path
from userprofile.forms import LoginForm

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path(
        "log-in/",
        views.LoginView.as_view(
            template_name="userprofile/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("log-out/", views.LogoutView.as_view(), name="logout"),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/leads/", include("lead.urls")),
    path("dashboard/teams/", include("team.urls")),
    path("dashboard/clients/", include("client.urls")),
    path("dashboard/", include("userprofile.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/client/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Client(models.Model):
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='clients',
                                   on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name


class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='clientfiles')
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username


class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

crm/client/forms.py
from django import forms
from .models import Client, Comment, ClientFile


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'description')


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)

crm/client/views.py
import csv

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from team.models import Team

from .forms import AddClientForm, AddCommentForm, AddFileForm
from .models import Client


@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)

    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="clients.csv"'},
    )
    writer = csv.writer(response)
    writer.writerow(["Client", "Description", "Created at", "Created by"])

    for client in clients:
        writer.writerow(
            [
                client.name,
                client.description,
                client.created_at,
                client.created_by,
            ]
        )

    return response


@login_required
def clients_list(request):
    clients = Client.objects.filter(created_by=request.user)

    return render(request, "client/clients_list.html", {"clients": clients})


@login_required
def clients_add_file(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == "POST":
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.client_id = pk
            file.created_by = request.user
            file.save()

            return redirect("clients:detail", pk=pk)
    return redirect("clients:detail", pk=pk)


@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == "POST":
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.client = client
            comment.save()

            return redirect("clients:detail", pk=pk)
    else:
        form = AddCommentForm()

    return render(
        request,
        "client/clients_detail.html",
        {"client": client, "form": form, "fileform": AddFileForm()},
    )


@login_required
def add_client(request):
    team = request.user.userprofile.active_team

    if request.method == "POST":
        form = AddClientForm(request.POST)

        if form.is_valid():
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = team
            client.save()

            messages.success(request, "Успешно создан.")

            return redirect("clients:list")
    else:
        form = AddClientForm()

    return render(
        request, "client/add_client.html", {"form": form, "team": team}
    )


@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()

    messages.success(request, "Успешно удалено.")

    return redirect("clients:list")


@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == "POST":
        form = AddClientForm(request.POST, instance=client)

        if form.is_valid():
            client = form.save()

            messages.success(request, "Успешно изменён.")
            return redirect("clients:list")

    else:
        form = AddClientForm(instance=client)

        return render(request, "client/clients_edit.html", {"form": form})

crm/client/templates/client/add_client.html
{% extends 'core/base.html' %}

{% block title %}Добавить{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-xl">Добавить</h1>

    {% if team.plan.max_clients > team.clients.all|length %}
        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-4 px-8 bg-violet-500 text-white rounded-xl">Добавить</button>
        </form>
    {% else %}
        <div class="px-6 py-4 bg-red-400 rounded-xl text-white">Твоя команда достигла максимальное число клиентов. Менеджер может обновить ваш план!</div>

    {% endif %}
</div>



{% endblock %}

crm/client/templates/client/clients_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-xl">{{ client.name }}</h1>

    {% if client.description %}
        <p class="font-semibold">Имя</p>
        <p class="mb-2">{{ client.description }}</p>
    {% endif %}

    <p class="font-semibold">Создан</p>
    <p class="mb-2">{{ client.created_at|date:"M-d-Y H:i" }}</p>

    <p class="font-semibold">Изменён</p>
    <p class="mb-6">{{ client.modified_at|date:"M-d-Y H:i" }}</p>

    <hr class="my-5">
    <a href="{% url 'clients:edit' client.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Изменить</a>
    <a href="{% url 'clients:delete' client.id %}" class="py-2 px-4 rounded-xl bg-red-500 text-white">Удалить</a>

    <hr class="my-5">

    <h2 class="mb-6 text-xl">Комментарии:</h2>

    <div class="space-y-4">
        {% for comment in client.comments.all %}
            <div class="bg-gray-100 py-6 px-6 rounded-xl">
                <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>
                {{ comment.content }}
            </div>
        {% endfor %}
    </div>
    <form method="post" action="{% url 'clients:add_comment' client.id %}">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-2 px-4 rounded-xl bg-teal-500 text-white">Отправить</button>
    </form>

    <hr class="my-5">

    <h2 class="mb-6 text-xl">Файлы:</h2>

    <div class="space-y-4">
        {% for file in client.files.all %}
            <div class="bg-gray-100 py-6 px-6 rounded-xl">
                <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>

                <a href="{{ file.file.url }}">Загрузить</a>

            </div>
        {% endfor %}
    </div>

    <form method="post" action="{% url 'clients:add_file' client.id %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{ fileform.as_p }}

        <button class="py-2 px-4 rounded-xl bg-teal-500 text-white">Отправить</button>
    </form>

    <hr class="my-5">
    <a href="{% url 'clients:list' %}" class="py-2 px-4 rounded-xl bg-gray-500 text-white">Вернуться к списку</a>



</div>



{% endblock %}

crm/client/templates/client/clients_edit.html
{% extends 'core/base.html' %}

{% block title %}Изменить{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-xl">Изменить</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-8 bg-violet-500 text-white rounded-xl">Подтвердить</button>
    </form>
</div>



{% endblock %}

crm/client/templates/client/clients_list.html
{% extends 'core/base.html' %}

{% block title %}Клиенты{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="mb-4 text-xl">Клиенты</h1>


    <a href="{% url 'clients:add' %}" class='inline-block py-4 px-6 bg-violet-600 rounded-xl text-white'>Добавить</a>
    <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 rounded-xl bg-teal-500 text-white">Экспорт</a>


    {% if clients %}
    <div class="mt-6 flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Имя</p>

    </div>
    {% for client in clients %}
        <div class="flex justify-between">
            <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                <a href="{% url 'clients:detail' client.id %}">{{ client.name }}</a>
            </p>

        </div>

    {% endfor %}
    {% else %}
    <p class="mt-6 py-2">Еще нет клиентов в базе</p>
    {% endif %}
</div>


{% endblock %}